/**
 * ============================================================================
 * DATA CONTRACTS & TYPE DEFINITIONS (study.ts)
 * ============================================================================
 * 
 * Key Presentation Concept: Type Safety from AI Prompt to UI Render
 * 
 * How to explain:
 * - These interfaces define the exact shape of the JSON generated by Gemini.
 * - By mirroring these TypeScript types with the Gemini `responseSchema` in
 *   `aiService.ts`, we ensure strict compile-time and runtime type safety.
 * ============================================================================
 */

/** Single multiple-choice quiz question generated by Gemini */
export interface QuizQuestion {
  id?: number;
  question: string;
  options: string[];       // Exactly 4 options (A, B, C, D)
  answerIndex: number;     // 0-indexed correct option (0, 1, 2, or 3)
  explanation: string;     // Why this answer is correct
}

/** Complete study package generated by Gemini Structured Outputs */
export interface GeneratedStudyData {
  topic: string;             // Topic title
  explanation: string;       // Core high-level explanation
  keyPoints: string[];       // 3 concise takeaway bullets
  practicalExample: string;  // Applied code or real-world example
  quizQuestions: QuizQuestion[]; // 3 multiple-choice questions
  challenge: string;         // Hands-on challenge for the learner
}

/** Full study session document stored in Cloud Firestore */
export interface StudySession extends GeneratedStudyData {
  id?: string;               // Unique Firestore document ID
  userId?: string;           // Firebase Auth UID of the owner
  createdAt: number;         // Unix timestamp (Date.now())
}

