import React from 'react';
import { BookOpen, CheckCircle, Code2, Target, HelpCircle } from 'lucide-react';
import { StudySession } from '../types/study';
import { QuizSection } from './QuizSection';

interface StudySessionViewProps {
  session: StudySession;
}

/**
 * ============================================================================
 * STUDY SESSION VIEW COMPONENT (StudySessionView.tsx)
 * ============================================================================
 * 
 * Role in Architecture:
 * - The primary presentation view for the AI-generated study material.
 * - Displays the 5 key pedagogical pillars generated by Gemini:
 *   1. Clear Explanation: Plain-English summary of the concept.
 *   2. Key Points: Bulleted breakdown of essential takeaways.
 *   3. Practical Example: Realistic code snippet or applied scenario.
 *   4. Your Challenge: Hands-on exercise for the student to practice.
 *   5. Knowledge Check: Interactive multi-choice quiz with instant feedback.
 * ============================================================================
 */
export const StudySessionView: React.FC<StudySessionViewProps> = ({ session }) => {
  return (
    <div className="output-card card">

      {/* ── 1. TOPIC HEADER & METADATA TAGS ── */}
      <div className="output-header">
        <h2 className="output-topic-title">{session.topic}</h2>
        <div className="output-meta">
          <span className="output-meta-tag tag-blue">Gemini</span>
          <span className="output-meta-tag tag-green">Firebase AI Logic</span>
        </div>
      </div>

      {/* ── 2. CONCEPT EXPLANATION ── */}
      <div className="output-section">
        <div className="section-header">
          <span className="section-icon icon-blue"><BookOpen size={13} /></span>
          Explanation
        </div>
        <p className="explanation-text">{session.explanation}</p>
      </div>

      {/* ── 3. KEY TAKEAWAYS (LIST) ── */}
      <div className="output-section">
        <div className="section-header">
          <span className="section-icon icon-green"><CheckCircle size={13} /></span>
          Key Points
        </div>
        <ul className="key-points-list">
          {session.keyPoints.map((point, idx) => (
            <li key={idx} className="key-point-item">
              <span className="point-number">{idx + 1}</span>
              <span>{point}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* ── 4. PRACTICAL REAL-WORLD EXAMPLE ── */}
      <div className="output-section">
        <div className="section-header">
          <span className="section-icon icon-purple"><Code2 size={13} /></span>
          Practical Example
        </div>
        <div className="example-box">{session.practicalExample}</div>
      </div>

      {/* ── 5. STUDENT HANDS-ON CHALLENGE ── */}
      <div className="output-section">
        <div className="section-header">
          <span className="section-icon icon-yellow"><Target size={13} /></span>
          Your Challenge
        </div>
        <div className="challenge-box">{session.challenge}</div>
      </div>

      {/* ── 6. INTERACTIVE QUIZ SECTION ── */}
      <div className="output-section">
        <div className="section-header">
          <span className="section-icon icon-cyan"><HelpCircle size={13} /></span>
          Knowledge Check
        </div>
        <QuizSection questions={session.quizQuestions} />
      </div>

    </div>
  );
};

